// GENERATED by scripts_code/sync_config.py from cad/config/dimensions.json - DO NOT HAND-EDIT
// Units: inches. Coordinate origin: bed-floor top, centerline, inner face of bed front wall.
// +X forward (toward cab), +Y left (driver), +Z up.

// Build defaults; override with -D (see build_variant.scad).
FRAME_SYSTEM = "HYBRID";
TRUCK = "SHORT";

WINDOW_NOSE_ENABLED = true;
camper_lower_length = 78.0;
camper_body_width = 80.0;
camper_lower_tub_width = 63.0;
tub_side_clearance = 0.75;
wheel_well_clearance = 1.0;
body_rail_clearance = 1.0;
camper_front_gap = 0.5;
camper_to_cab_clearance = 4.0;
interior_height = 80.0;
floor_sandwich = 3.0;
wall_thickness = 1.75;
roof_thickness = 3.5;
roof_crown = 0.75;
skin_thickness = 0.05;
insulation_thickness = 1.5;
body_corner_radius = 3.0;
roof_edge_radius = 2.0;
nose_projection = 24.0;
nose_top_setback = 10.0;
nose_floor_thickness = 2.5;
door_width = 26.0;
door_height = 72.0;
door_sill_above_floor = 1.0;
door_offset_y = 0.0;
window_side_width = 24.0;
window_side_height = 15.0;
window_side_center_above_floor = 50.0;
window_side_center_from_rear = 30.0;
window_nose_width = 20.0;
window_nose_height = 9.0;
util_profile = "TSLOT_1010";
utility_rail_left_count = 3;
utility_rail_right_count = 3;
utility_rail_front_count = 1;
utility_rail_side_heights = [24.0, 44.0, 64.0];
utility_rail_front_height = 36.0;
utility_rail_end_inset = 2.0;
roof_rack_boss_from_rear = [10.0, 44.0, 78.0];
roof_rack_boss_edge_inset = 6.0;
roof_rack_boss_diameter = 2.0;
roof_rack_boss_height = 0.75;
power_zone_length = 24.0;
power_zone_width = 20.0;
power_zone_from_front = 2.0;
wire_chase_size = 3.0;
human_height = 79.0;
truck_bed_floor_height = 34.0;
truck_bed_rail_height = 20.4;
truck_bed_floor_width = 69.3;
truck_bed_inner_width_top = 69.3;
truck_bed_rail_width = 5.3;
truck_tailgate_opening_width = 65.0;
truck_wheel_well_width = 50.6;
truck_wheel_well_height = 10.5;
truck_wheel_well_length = 34.0;
truck_cab_height_above_bed = 46.0;
truck_cab_to_bed_clearance = 4.0;
truck_bed_front_wall_thickness = 1.5;
truck_cab_width = 79.0;
truck_cab_roof_length = 58.0;
truck_hood_height_above_bed = 23.0;
truck_tire_diameter = 35.0;
truck_track_width = 68.0;
truck_windshield_run = 24.0;
truck_front_overhang = 38.0;
truck_body_bottom_below_bed = 14.0;
truck_beltline_above_bed = 18.0;
truck_bed_length = TRUCK == "LONG" ? 98.0 : 81.9;
truck_rear_axle_from_bulkhead = TRUCK == "LONG" ? 52.0 : 48.0;
truck_wheelbase = TRUCK == "LONG" ? 176.0 : 159.8;
tub_base_width = 49.1;
tub_step_z = 11.5;
camper_lower_tub_height = 21.4;
camper_front_x = -0.5;
camper_rear_x = -78.5;
interior_floor_z = 3.0;
ceiling_z = 83.0;
roof_eave_z = 86.5;
roof_crown_z = 87.25;
nose_bottom_z = 50.0;
nose_floor_z = 52.5;
nose_interior_height = 30.5;
nose_front_x = 23.5;
overall_length = 102.0;
overall_height = 87.25;
ground_to_eave = 120.5;
ground_to_crown = 121.25;
body_interior_width = 76.5;
tub_interior_base_width = 45.6;
interior_length = 74.5;
cab_back_x = 5.5;
nose_over_cab = 18.0;
bed_length_unused = TRUCK == "LONG" ? 19.5 : 3.4;
rear_axle_x = TRUCK == "LONG" ? -52.0 : -48.0;
floor_mid_ahead_of_axle = TRUCK == "LONG" ? 12.5 : 8.5;
door_bottom_z = 4.0;
door_top_z = 76.0;
window_side_center_z = 53.0;
headroom_6ft7 = 1.0;

// Materials: [name, density_lb_in3]
MATERIALS = [["AL6061T6", 0.0975], ["AL5052H32", 0.0968], ["AL6105T5", 0.0975], ["XPS", 0.0012]];

// Profiles: [name, kind, w, h, wall, material, lb_per_in]
PROFILES = [["TUBE_1X1_083", "SQUARE_TUBE", 1.0, 1.0, 0.083, "AL6061T6", 0.0291], ["TUBE_1X1_125", "SQUARE_TUBE", 1.0, 1.0, 0.125, "AL6061T6", 0.0426], ["TUBE_1X2_125", "RECT_TUBE", 1.0, 2.0, 0.125, "AL6061T6", 0.067], ["TUBE_2X2_125", "SQUARE_TUBE", 2.0, 2.0, 0.125, "AL6061T6", 0.0914], ["TSLOT_1010", "TSLOT", 1.0, 1.0, 0.0, "AL6105T5", 0.0425], ["TSLOT_1020", "TSLOT", 1.0, 2.0, 0.0, "AL6105T5", 0.0763], ["TSLOT_1515", "TSLOT", 1.5, 1.5, 0.0, "AL6105T5", 0.0848]];

// Owner accessory T-slot rails: [id, length, [x,y,z] start, axis]
UTIL_RAILS = [["UTIL-L-01", 70.5, [-74.75, 38.25, 27.0], "X"], ["UTIL-L-02", 70.5, [-74.75, 38.25, 47.0], "X"], ["UTIL-L-03", 70.5, [-74.75, 38.25, 67.0], "X"], ["UTIL-R-01", 70.5, [-74.75, -38.25, 27.0], "X"], ["UTIL-R-02", 70.5, [-74.75, -38.25, 47.0], "X"], ["UTIL-R-03", 70.5, [-74.75, -38.25, 67.0], "X"], ["UTIL-F-01", 72.5, [-2.25, -36.25, 39.0], "Y"]];
