"""Shared config loading and derived geometry for MINUTEMAN scripts.

Everything geometric that more than one consumer needs (OpenSCAD, drawings, reports) is derived here,
once, from cad/config/dimensions.json. sync_config.py writes these derived values into
dimensions.scad so the model never re-derives them independently.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "cad" / "config" / "dimensions.json"
OPENSCAD = "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD"
OUTPUT = ROOT / "output" / "current_design"
PARTS_JSON = OUTPUT / "parts.json"

TAGS = ("FIXED", "PARAMETRIC", "PRELIMINARY", "VERIFY ON TRUCK")
STATUSES = ("CONCEPT", "CALCULATED", "MANUFACTURER VERIFIED", "PHYSICALLY TESTED",
            "PROFESSIONALLY REVIEWED", "NEEDS REVIEW")
GENERATED_HEADER = "GENERATED by scripts_code/{script} from cad/config/dimensions.json - DO NOT HAND-EDIT"


def load_config():
    with open(CONFIG) as f:
        return json.load(f)


def base_params(cfg, variant=None, overrides=None):
    """Flat {name: value} for one truck variant, with optional overrides (used for sensitivity)."""
    variant = variant or cfg["build"]["TRUCK"]["value"]
    p = {k: v["value"] for k, v in cfg["build"].items()}
    p["TRUCK"] = variant
    for section in ("camper", "truck"):
        p.update({k: v["value"] for k, v in cfg[section].items()})
    p.update({k: v["value"] for k, v in cfg["truck_variants"][variant].items() if isinstance(v, dict)})
    if overrides:
        p.update(overrides)
    return p


# (name, label, tag, function) - tag describes the derived dimension's confidence.
DERIVED = [
    ("tub_base_width", "Lower tub base width (between wheel wells)", "VERIFY ON TRUCK",
     lambda p, d: p["truck_wheel_well_width"] - 2 * p["tub_side_clearance"]),
    ("tub_step_z", "Lower tub step height above bed floor (clears wheel wells)", "VERIFY ON TRUCK",
     lambda p, d: p["truck_wheel_well_height"] + p["wheel_well_clearance"]),
    ("camper_lower_tub_height", "Lower tub height / body underside above bed floor", "VERIFY ON TRUCK",
     lambda p, d: p["truck_bed_rail_height"] + p["body_rail_clearance"]),
    ("camper_front_x", "Camper front face X", "PRELIMINARY", lambda p, d: -p["camper_front_gap"]),
    ("camper_rear_x", "Camper rear face X", "PRELIMINARY",
     lambda p, d: d["camper_front_x"] - p["camper_lower_length"]),
    ("interior_floor_z", "Interior floor above bed floor", "PRELIMINARY", lambda p, d: p["floor_sandwich"]),
    ("ceiling_z", "Ceiling above bed floor", "PRELIMINARY",
     lambda p, d: d["interior_floor_z"] + p["interior_height"]),
    ("roof_eave_z", "Roof eave above bed floor", "PRELIMINARY",
     lambda p, d: d["ceiling_z"] + p["roof_thickness"]),
    ("roof_crown_z", "Roof crown (highest point) above bed floor", "PRELIMINARY",
     lambda p, d: d["roof_eave_z"] + p["roof_crown"]),
    ("nose_bottom_z", "Nose underside above bed floor", "VERIFY ON TRUCK",
     lambda p, d: p["truck_cab_height_above_bed"] + p["camper_to_cab_clearance"]),
    ("nose_floor_z", "Nose interior floor above bed floor", "VERIFY ON TRUCK",
     lambda p, d: d["nose_bottom_z"] + p["nose_floor_thickness"]),
    ("nose_interior_height", "Nose interior clear height", "VERIFY ON TRUCK",
     lambda p, d: d["ceiling_z"] - d["nose_floor_z"]),
    ("nose_front_x", "Nose lower front edge X", "PARAMETRIC",
     lambda p, d: d["camper_front_x"] + p["nose_projection"]),
    ("overall_length", "Overall camper length (rear face to nose tip)", "PARAMETRIC",
     lambda p, d: p["camper_lower_length"] + p["nose_projection"]),
    ("overall_height", "Overall camper height (tub bottom to crown)", "PRELIMINARY", lambda p, d: d["roof_crown_z"]),
    ("ground_to_eave", "Ground to roof eave on truck", "VERIFY ON TRUCK",
     lambda p, d: p["truck_bed_floor_height"] + d["roof_eave_z"]),
    ("ground_to_crown", "Ground to roof crown on truck (travel height, excl. rack)", "VERIFY ON TRUCK",
     lambda p, d: p["truck_bed_floor_height"] + d["roof_crown_z"]),
    ("body_interior_width", "Main body interior width", "PRELIMINARY",
     lambda p, d: p["camper_body_width"] - 2 * p["wall_thickness"]),
    ("tub_interior_base_width", "Interior floor width (tub base)", "VERIFY ON TRUCK",
     lambda p, d: d["tub_base_width"] - 2 * p["wall_thickness"]),
    ("interior_length", "Main body interior length (excl. nose)", "PRELIMINARY",
     lambda p, d: p["camper_lower_length"] - 2 * p["wall_thickness"]),
    ("cab_back_x", "Cab back face X", "VERIFY ON TRUCK",
     lambda p, d: p["truck_bed_front_wall_thickness"] + p["truck_cab_to_bed_clearance"]),
    ("nose_over_cab", "Nose overlap forward of cab back", "VERIFY ON TRUCK",
     lambda p, d: d["nose_front_x"] - d["cab_back_x"]),
    ("bed_length_unused", "Bed length behind camper (unused)", "VERIFY ON TRUCK",
     lambda p, d: p["truck_bed_length"] - p["camper_lower_length"] - p["camper_front_gap"]),
    ("rear_axle_x", "Rear axle X", "VERIFY ON TRUCK", lambda p, d: -p["truck_rear_axle_from_bulkhead"]),
    ("floor_mid_ahead_of_axle", "Camper floor midpoint ahead of rear axle", "VERIFY ON TRUCK",
     lambda p, d: (d["camper_front_x"] + d["camper_rear_x"]) / 2 - d["rear_axle_x"]),
    ("door_bottom_z", "Door sill above bed floor", "PRELIMINARY",
     lambda p, d: d["interior_floor_z"] + p["door_sill_above_floor"]),
    ("door_top_z", "Door head above bed floor", "PRELIMINARY",
     lambda p, d: d["door_bottom_z"] + p["door_height"]),
    ("window_side_center_z", "Side window center above bed floor", "PARAMETRIC",
     lambda p, d: d["interior_floor_z"] + p["window_side_center_above_floor"]),
    ("headroom_6ft7", "Headroom over a 6'7\" person", "FIXED",
     lambda p, d: p["interior_height"] - p["human_height"]),
]


def derive(p):
    d = {}
    for name, _label, _tag, fn in DERIVED:
        d[name] = round(fn(p, d), 4)
    return d


def params(cfg=None, variant=None, overrides=None):
    """Base + derived values in one flat dict."""
    cfg = cfg or load_config()
    p = base_params(cfg, variant, overrides)
    p.update(derive(p))
    return p


def utility_rails(p):
    """Owner accessory T-slot rail layout. One list consumed by OpenSCAD (via sync) and reports."""
    rails = []
    inset = p["utility_rail_end_inset"]
    side_len = p["interior_length"] - 2 * inset
    x0 = p["camper_rear_x"] + p["wall_thickness"] + inset
    y_wall = p["body_interior_width"] / 2
    for side, sgn, count in (("L", 1, p["utility_rail_left_count"]), ("R", -1, p["utility_rail_right_count"])):
        for i in range(count):
            h = p["utility_rail_side_heights"][i]
            rails.append({"id": "UTIL-%s-%02d" % (side, i + 1), "wall": side, "length": side_len,
                          "start": [x0, sgn * y_wall, p["interior_floor_z"] + h], "axis": "X"})
    front_len = p["body_interior_width"] - 2 * inset
    for i in range(p["utility_rail_front_count"]):
        rails.append({"id": "UTIL-F-%02d" % (i + 1), "wall": "F", "length": front_len,
                      "start": [p["camper_front_x"] - p["wall_thickness"], -front_len / 2,
                                p["interior_floor_z"] + p["utility_rail_front_height"]], "axis": "Y"})
    return rails


def skin_faces(p):
    """Flat-pattern approximation of every exterior envelope face (sq in). Corner radii ignored.

    Returns list of dicts: id, description, width, height, area, group (walls/roof/nose/floor).
    """
    L = p["camper_lower_length"]
    W = p["camper_body_width"]
    tw, tb = p["camper_lower_tub_width"], p["tub_base_width"]
    z_step, z_body = p["tub_step_z"], p["camper_lower_tub_height"]
    body_h = p["roof_eave_z"] - z_body
    nose_h = p["roof_eave_z"] - p["nose_bottom_z"]
    nose_top_len = p["nose_projection"] - p["nose_top_setback"]
    front_body_h = p["nose_bottom_z"] - z_body
    tub_end_area = tb * z_step + tw * (z_body - z_step)
    door = p["door_width"] * p["door_height"]
    win_side = p["window_side_width"] * p["window_side_height"]
    win_nose = p["window_nose_width"] * p["window_nose_height"] if p["WINDOW_NOSE_ENABLED"] else 0
    nose_front_len = math.hypot(nose_h, p["nose_top_setback"])
    f = []

    def add(id_, desc, w, h, group, area=None, cut=0.0):
        f.append({"id": id_, "description": desc, "width": round(w, 2), "height": round(h, 2),
                  "area": round((area if area is not None else w * h) - cut, 1), "group": group})

    for s, name in (("L", "Left"), ("R", "Right")):
        add("SKIN-%s-01" % s, "%s body side" % name, L, body_h, "walls", cut=win_side)
        add("SKIN-%s-02" % s, "%s nose side (trapezoid)" % name, p["nose_projection"], nose_h, "nose",
            area=(p["nose_projection"] + nose_top_len) / 2 * nose_h)
        add("SKIN-%s-03" % s, "%s tub side, upper" % name, L, z_body - z_step, "walls")
        add("SKIN-%s-04" % s, "%s tub side, lower" % name, L, z_step, "walls")
        add("SKIN-%s-05" % s, "%s tub step ledge" % name, L, (tw - tb) / 2, "walls")
        add("SKIN-%s-06" % s, "%s body underside overhang" % name, L, (W - tw) / 2, "walls")
    add("SKIN-F-01", "Front tub face (stepped)", tw, z_body, "walls", area=tub_end_area)
    add("SKIN-F-02", "Front body face below nose", W, front_body_h, "walls")
    add("SKIN-NOSE-01", "Nose underside", W, p["nose_projection"], "nose")
    add("SKIN-NOSE-02", "Nose raked front face", W, nose_front_len, "nose", cut=win_nose)
    add("SKIN-B-01", "Rear face incl. tub (door cut out)", W, body_h + z_body, "walls",
        area=W * body_h + tub_end_area, cut=door)
    add("SKIN-ROOF-01", "Roof", L + nose_top_len, W, "roof")
    return f


def surface_areas(p):
    faces = skin_faces(p)
    areas = {g: sum(x["area"] for x in faces if x["group"] == g) for g in ("walls", "roof", "nose")}
    areas["skin_total"] = sum(areas.values())
    areas["floor_footprint"] = p["tub_base_width"] * p["camper_lower_length"]
    areas["insulated"] = areas["skin_total"]
    return areas



def fmt_in(x):
    """Inches as decimal plus feet-inches, e.g. 120.5 -> 120.50 (10'-0.5")."""
    ft = int(x // 12)
    inch = x - 12 * ft
    return '%.2f (%d\'-%s")' % (x, ft, ("%.2f" % inch).rstrip("0").rstrip("."))
